export default Object.freeze({
  Bg_Img: require('../assets/images/common/bg_Img.png'),
  GoBack: require('../assets/images/common/back.png'),
  Splash: require('../assets/images/splash/logo.png'),
  Finger: require('../assets/images/finger_id_access.png'),
  test: require('../assets/images/test.jpg'),
  test2: require('../assets/images/test2.png'),
  BackPng: require('../assets/images/back.png'),
  profile: require('../assets/images/profile.png'),
  Chat: require('../assets/images/chat.png'),
  Mic: require('../assets/images/footer_mic.png'),
  Ic_video: require('../assets/images/ic_video.png'),
  Ic_Next: require('../assets/images/ic_next.png'),
  Empty_Prof_Pic: require('../assets/images/ic_empty_profile_pic.png'),
  Checkbox_Active: require('../assets/images/ic_checkbox_active.png'),
  Checkbox_Normal: require('../assets/images/ic_checkbox_normal.png'),
  Add_status: require('../assets/images/ic_add_my_status.png'),
  ic_Profile: require('../assets/images/ic_profile.png'),
  ic_Notifications: require('../assets/images/ic_notifications.png'),
  ic_Accounts: require('../assets/images/ic_accounts.png'),
  ic_Profile_Camera: require('../assets/images/ic_profile_camera.png'),
});
